title: "Seu Nome"
email: your-email@example.com
description: "Blog com o objetivo de compartilhar conhecimento."
baseurl: "" # se estiver no root do repositório, deixe vazio
url: "https://username.github.io" # Substitua pelo seu URL do GitHub Pages

# Markdown Processamento
markdown: kramdown
theme: minima

# Excluir da geração
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# Permalinks
permalink: /:year/:month/:day/:title/

# Links da rede social (opcional)
github_username: seu-github-username
linkedin_username: seu-linkedin-username
rss: rss
