title: "Airton Carneiro"
description: "Senior Data Engineer | SQL, AWS, Data Platforms e GenAI"
baseurl: ""
url: "https://airtoncarneiro.github.io"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: minima
permalink: /:year/:month/:day/:title/
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "node_modules"
  - "vendor/"
github_username: airtoncarneiro
rss: feed.xml
